// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imkkkcbpyivssqgyvuft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlta2trY2JweWl2c3NxZ3l2dWZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MzA4NzQsImV4cCI6MjA2MTUwNjg3NH0.X_LMCb4T-_kXl1WWwUGgTneY_VYo7wg6iB66sJh9ESs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);